#!/bin/sh

# Whenever Globus brings out a new release, some of the packages
# do not jump version but autogenerated files are updated.
# Because the timestamps change, so does the checksum of the
# tarball.

# This script extracts the new checksums from a given collection
# of packages and will replace the checksums in the Portfiles
# corresponding to those packages.

# Most package names and ports correspond one-to-one modulo
# replacing the '_' with '-', with the exception of gpt
# which is called grid-packaging-tools

set -e

VERBOSE=0

usage() {
    echo "Usage: $0 <package-dir> [ <port-dir> ]

Collect checksums in the Globus toolkit package-dir and
update the corresponding Portfiles in the port-dir.
Use '.' if port-dir is not given.
"
}

if [ $# -lt 1 ]; then
    usage
    exit 2
else
    PKG_DIR="$1"
    PORT_DIR="$2"
fi

if [ -z "$PORT_DIR" ] ; then
    PORT_DIR=.
fi

if ! cd "$PORT_DIR" ; then
    echo "Can't change directory to $PORT_DIR" >&2
    exit 1
fi

PKGS=`ls -d globus-* myproxy grid-packaging-tools`

cd "$OLDPWD"

for p in $PKGS ; do
    case $p in
	grid-packaging-tools)
	    name=gpt
	    ;;
	globus-clients)
	    # skip it because it's our metapackage
	    continue
	    ;;
	*)
	    name=`echo $p | tr '-' '_'`
    esac

    file_name=`ls $PKG_DIR/$name-*.tar.gz`
    
    r160=`openssl rmd160 $file_name | cut -f 2 -d ' '`
    sha=`openssl sha256 $file_name | cut -f 2 -d ' '`
	
    if [ "$VERBOSE" -gt 0 ] ; then
	echo $p $r160 $sha
    fi

    sed -i.bak "s/ *sha256.*/                            sha256 $sha \\\\/" "$PORT_DIR/$p/Portfile"
    sed -i.bak "s/ *rmd160.*/                            rmd160 $r160/" "$PORT_DIR/$p/Portfile"
done


